Service Payment
htilssu/e-wallet-fe pull request #48
Opened 2024-07-16 09:10 UTC by Tuan980Blue

Add giúp mình add để tạo branch mới

2024-07-16 09:25 UTC, htilssu requested changes

2024-07-17 02:50 UTC, Tuan980Blue commented on src/components/otpverify/OTPverification.jsx
> +    const [resendTime, setResendTime] = useState(10);
wait

2024-07-17 03:11 UTC, Tuan980Blue commented on src/components/home/Home.jsx
>                                      <Card icon={<FaDownload size={30} className={"text-green-500"}/>} title="Nạp tiền"
oke minh lam sau

2024-07-17 03:11 UTC, Tuan980Blue commented on src/components/otpverify/OTPverification.jsx
> +    const [resendTime, setResendTime] = useState(10);
cai nay tutu nha

2024-07-17 03:17 UTC, htilssu approved these changes

2024-07-17 03:18 UTC, merged